name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests using Xcode
        run: |
          xcodebuild clean build test -scheme IS322_CalculatorApp -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.2'
